#!/opt/pwn.college/bash

if [ -t 1 ] || [ -f /dev/fd/1 ]
then
	fold -s <<< "You must redirect my standard output into '/challenge/planet'!"
else
	fold -s <<< "This secret data must directly make it to /challenge/planet over my stdout. Don't try to copy-paste it; it changes too fast."
	cat /challenge/.challenge-key-stdout
fi

if [ -t 2 ] || [ -f /dev/fd/2 ]
then
	fold -s >&2 <<< "You must redirect my standard error into '/challenge/the'!"
else
	fold -s >&2 <<< "This secret data must directly make it to /challenge/the over my stderr. Don't try to copy-paste it; it changes too fast."
	cat /challenge/.challenge-key-stderr >&2
fi
