#!/opt/pwn.college/bash

read CORRECT < /challenge/.challenge-key-stdout
read ATTEMPT < <(tail -n 1)

if [ "$CORRECT" == "$ATTEMPT" ]
then
	echo "$CORRECT" > /challenge/.the
else
	fold -s >&2 <<< "Are you sure you're properly redirecting /challenge/hack's output into '/challenge/the'?"
fi
