#!/opt/pwn.college/bash
# HARDENED-PATH
set -euo pipefail
IFS=' 	
'
unalias -a 2>/dev/null || true
unset BASH_ENV ENV CDPATH SHELLOPTS EDITOR VISUAL PAGER SYSTEMD_PAGER LESSOPEN GIT_EDITOR GIT_PAGER LD_PRELOAD LD_LIBRARY_PATH
PATH="/usr/sbin:/usr/bin:/sbin:/bin"; export PATH
umask 022

if /bin/ps -ef | grep -q '[d]ont_run'
then
	/usr/bin/fold -s <<< "Nope! /challenge/dont_run is still running! You gotta terminate it before I give you the flag!"
	exit
fi

/usr/bin/fold -s <<< "Great job! Here is your payment:"
/bin/cat /flag
