#!/usr/bin/env python3

import subprocess
import random
import string
import time

flag_length = int(subprocess.check_output(['/challenge/.flaglen']).strip())
content_length = flag_length - 13

while True:
    random_content = ''.join(random.choices(string.ascii_letters + string.digits, k=content_length))
    print(f"pwn.college{{{random_content}}}")
    time.sleep(0.01)
