#!/opt/pwn.college/bash
# HARDENED-PATH
set -euo pipefail
IFS=' 	
'
unalias -a 2>/dev/null || true
unset BASH_ENV ENV CDPATH SHELLOPTS EDITOR VISUAL PAGER SYSTEMD_PAGER LESSOPEN GIT_EDITOR GIT_PAGER LD_PRELOAD LD_LIBRARY_PATH
PATH="/usr/sbin:/usr/bin:/sbin:/bin"; export PATH
umask 022

if [ -z "$DOIT" ]
then
	export DOIT=yes
	exec -a $0 bash < $0
fi

echo "Yahaha, you found me! Here is your flag:"
/bin/cat /flag
echo "Now I will sleep for a while (so that you could find me with 'ps')."
sleep 6h
