#!/opt/pwn.college/bash

DIRECTORY_TO_GO_TO="/challenge/.state"

FINAL_DIRECTORY="/"
DIRECTORIES="something"

generate_random_directory() {
  while [[ -n $DIRECTORIES ]]; do
    DIRECTORIES=$(find $FINAL_DIRECTORY -maxdepth 1 -type d -executable -printf '%f\n' | tail -n +2 )
    NUM_OF_DIRECTORIES=$(echo "$DIRECTORIES" | wc -l)
    RANDOM_DIRECTORY_INDEX=$(($RANDOM % $NUM_OF_DIRECTORIES + 1))
    RANDOM_DIRECTORY=$(echo "$DIRECTORIES" | head -n $RANDOM_DIRECTORY_INDEX | tail -n 1)
    FINAL_DIRECTORY="${FINAL_DIRECTORY}/${RANDOM_DIRECTORY}"
  done
}

if [[ -f $DIRECTORY_TO_GO_TO ]]; then
  NEEDED=$(cat $DIRECTORY_TO_GO_TO)
else
  generate_random_directory
  STRING_LENGTH=${#FINAL_DIRECTORY}
  NEEDED=${FINAL_DIRECTORY:1:STRING_LENGTH - 2}
  echo "$NEEDED" > $DIRECTORY_TO_GO_TO
fi

if [ "$PWD" != "$NEEDED" ]
then
        echo -e "${COLOR_RED}Incorrect...${COLORLESS}"
        echo "You are not currently in the $NEEDED directory."
        echo 'Please use the `cd` utility to change directory appropriately.'
        exit 1
fi

if [ "${0:0:1}" != "/" ]
then
        echo -e "${COLOR_RED}Incorrect...${COLORLESS}"
        echo "You did not call this challenge using an absolute path!"
        echo "An absolute path is anchored at the root of the filesystem, so it starts with /"
        exit 1
fi

echo -e "${COLOR_GREEN}Correct!!!${COLORLESS}"
echo "$0 is an absolute path, invoked from the right directory!"
echo "Here is your flag:"
/bin/cat /flag
