#!/bin/bash

echo "bash: $0: command not found"
echo
fold -s <<< "You put spaces around your '=' in your assignment! This caused the shell to execute the '$0' command instead of setting the '$0' environment variable. Try again without spaces around '='!"
