#!/bin/bash
# HARDENED-PATH
set -euo pipefail
IFS=' 	
'
unalias -a 2>/dev/null || true
unset BASH_ENV ENV CDPATH SHELLOPTS EDITOR VISUAL PAGER SYSTEMD_PAGER LESSOPEN GIT_EDITOR GIT_PAGER LD_PRELOAD LD_LIBRARY_PATH
PATH="/usr/sbin:/usr/bin:/sbin:/bin"; export PATH
umask 022

/bin/fold -w $(/bin/tput cols) -s <<END
You cannot solve this challenge using /challenge/run.
To solve this challenge, you must set the PWN variable to the value "COLLEGE".
The challenge will detect this and give you the flag!
END
