#!/opt/pwn.college/bash

RANDOM=$(cksum /flag  | awk '{print $1}')
CANDIDATES=("/" "/tmp" "/usr/bin" "/var/log" "/etc/apt/sources.list.d" "/usr/share/doc" "/var/lib/apt/lists" )
NEEDED=${CANDIDATES[ $RANDOM % ${#CANDIDATES[@]} ]}

if [ "$PWD" != "$NEEDED" ]
then
	echo -e "${COLOR_RED}Incorrect...${COLORLESS}"
	echo "You are not currently in the $NEEDED directory."
	echo 'Please use the `cd` utility to change directory appropriately.'
	exit 1
fi

if [ "${0:0:1}" != "/" ]
then
	echo -e "${COLOR_RED}Inorrect...${COLORLESS}"
	echo "You did not call this challenge using an absolute path!"
	echo "An absolute path is anchored at the root of the filesystem, so it starts with /"
	exit 1
fi

echo -e "${COLOR_GREEN}Correct!!!${COLORLESS}"
echo "$0 is an absolute path, invoked from the right directory!"
echo "Here is your flag:"
cat /flag
