#!/opt/pwn.college/bash

if [ -f /tmp/.chained ] && [ -f /tmp/.and ]; then
    echo "Nice chaining! Flag: $(cat /flag)"
else
    fold -s <<< "Error: /challenge/first must be successfully chained with /challenge/second using &&!"
    exit 1
fi
