#!/opt/pwn.college/bash

if [ -f /tmp/.chained ] && [ -f /tmp/.and ]; then
    echo "Nice chaining! Flag: $(cat /flag)"
else
    echo "Error: /challenge/first must be successfully chained with this command using &&!"
    exit 1
fi
