#!/opt/pwn.college/bash
# HARDENED-PATH
set -euo pipefail
IFS=' 	
'
unalias -a 2>/dev/null || true
unset BASH_ENV ENV CDPATH SHELLOPTS EDITOR VISUAL PAGER SYSTEMD_PAGER LESSOPEN GIT_EDITOR GIT_PAGER LD_PRELOAD LD_LIBRARY_PATH
PATH="/usr/sbin:/usr/bin:/sbin:/bin"; export PATH
umask 022

/usr/bin/fold -s <<< "I could give you the flag... but I won't, until this process exits. Remember, you can force me to exit with Ctrl-C. Try it now!"

function flag {
	echo
	/usr/bin/fold -s <<< "Good job! You have used Ctrl-C to interrupt this process! Here is your flag:"
	/bin/cat /flag
}

trap flag SIGINT
sleep 6h
