#!/opt/pwn.college/bash
# HARDENED-PATH
set -euo pipefail
IFS=' 	
'
unalias -a 2>/dev/null || true
unset BASH_ENV ENV CDPATH SHELLOPTS EDITOR VISUAL PAGER SYSTEMD_PAGER LESSOPEN GIT_EDITOR GIT_PAGER LD_PRELOAD LD_LIBRARY_PATH
PATH="/usr/sbin:/usr/bin:/sbin:/bin"; export PATH
umask 022

if [ "$PWD" != "/challenge" ]
then
	/usr/bin/fold -s <<< "You must run me /challenge as the working directory. Try to change your working directory to /challenge, then re-run me."
elif [ ! -f /tmp/.good_cd ]
then
	/usr/bin/fold -s <<< "You've somehow made your working directory /challenge without using 'cd' and globbing. Please try again."
else
	/usr/bin/fold -s <<< "You ran me with the working directory of /challenge! Here is your flag:"
	/bin/cat /flag
fi
