#!/opt/pwn.college/bash
# HARDENED-PATH
set -euo pipefail
IFS=' 	
'
unalias -a 2>/dev/null || true
unset BASH_ENV ENV CDPATH SHELLOPTS EDITOR VISUAL PAGER SYSTEMD_PAGER LESSOPEN GIT_EDITOR GIT_PAGER LD_PRELOAD LD_LIBRARY_PATH
PATH="/usr/sbin:/usr/bin:/sbin:/bin"; export PATH
umask 022

if [[ $(/bin/ps -o stat= -p $$) == *+* ]]
then
	/usr/bin/fold -s <<< "You've started me in the foreground! You must start me in the background (by appending '&' to the command) to get the flag!"
	exit
fi

echo
echo
echo
/usr/bin/fold -s <<< "Yay, you started me in the background! Because of that, this text will probably overlap weirdly with the shell prompt, but you're used to that by now..."
echo
/usr/bin/fold -s <<< "Anyways! Here is your flag!"
/bin/cat /flag
