#!/opt/pwn.college/bash
# HARDENED-PATH
set -euo pipefail
IFS=' 	
'
unalias -a 2>/dev/null || true
unset BASH_ENV ENV CDPATH SHELLOPTS EDITOR VISUAL PAGER SYSTEMD_PAGER LESSOPEN GIT_EDITOR GIT_PAGER LD_PRELOAD LD_LIBRARY_PATH
PATH="/usr/sbin:/usr/bin:/sbin:/bin"; export PATH
umask 022

/bin/fold -s <<< "Trying to remove /flag..."

RM=$(which rm 2>/dev/null)
[ -n "$RM" ] && echo "Found 'rm' command at $RM. Executing!"
rm -f /flag

if ! [ -f /flag ]
then
	/bin/fold -s <<< "Uh oh, looks like I successfully removed the flag! That means you did not properly set PATH to keep me from finding 'rm'. Since the flag is gone, you will need to re-launch the challenge from the module page! Better luck next time."
fi
