#!/bin/bash

echo "bash: $0: command not found"
echo
fold -s <<< "You put spaces around your '=' in your assignment! This caused the shell to execute the '$0' command instead of assigning it to the environment variable as you intended. Try again without spaces around '='!"
