#!/opt/pwn.college/bash
# HARDENED-PATH
set -euo pipefail
IFS=' 	
'
unalias -a 2>/dev/null || true
unset BASH_ENV ENV CDPATH SHELLOPTS EDITOR VISUAL PAGER SYSTEMD_PAGER LESSOPEN GIT_EDITOR GIT_PAGER LD_PRELOAD LD_LIBRARY_PATH
PATH="/usr/sbin:/usr/bin:/sbin:/bin"; export PATH
umask 022

read -a ARGS < /tmp/.last_arg

if [ "$PWD" != "/challenge/files" ]
then
	/usr/bin/fold -s <<< "Error: please run with a working directory of /challenge/files!"
	exit 1
fi

if [ "${#ARGS[@]}" -eq 0 ]
then
	/usr/bin/fold -s <<< "Error: you called this command with no arguments! Please call me with one argument."
	exit 2
fi

if [ "${#ARGS[@]}" -gt 1 ]
then
	/usr/bin/fold -s <<< "Error: you called this command with more than 1 argument (pre-globbing)! Please call me with one argument."
	exit 3
fi

if [[ "${ARGS[0]}" != *"["* ]]
then
	/usr/bin/fold -s <<< "Error: you did not use a square bracket glob..."
	exit 4
fi

if [[ "${#ARGS[0]}" -gt 6 ]]
then
	/usr/bin/fold -s <<< "Error: your argument is too long! It must be 6 characters or less."
	exit 4
fi

if [ "$1" == "challenging" ] && [ "$2" == "educational" ] && [ "$3" == "pwning" ]
then
	/usr/bin/fold -s <<< "You got it! Here is your flag!"
	/bin/cat /flag
else
	/usr/bin/fold -s <<< "Your expansion did not expand to the requested files (challenging, educational, pwning). Instead, it expanded to:"
	echo "$@"
fi
