#!/opt/pwn.college/bash

RED='\033[1;31m'
GREEN='\033[1;32m'
NC='\033[0m'

if [ "${0:0:1}" != "/" ]
then
	echo -e "${RED}Inorrect...${NC}"
	echo "You did not call this challenge using an absolute path!"
	echo "An absolute path is anchored at the root of the filesystem, so it starts with /"
	exit 1
fi

echo -e "${GREEN}Correct!!!${NC}"
echo "$0 is an absolute path! Here is your flag:"
cat /flag
