#!/opt/pwn.college/python

import time
import os

flag = open("/flag").read()

while True:
    if len(os.listdir("/")) > 10 or len(os.listdir("/usr")) > 3 or len(os.listdir("/etc")) > 5 or os.path.exists("/flag"):
        print("Looks like you haven't wiped the system! We'll check again in 5 seconds...")
    else:
        print("YES! You did it again! Go read the flag!")
        os.chmod("/run", 0o000) # block off the nix stuff in PATH
        with open(os.urandom(4).hex(), "w") as f:
            f.write(flag)
        os.chmod("/flag", 0o444)
        break

    time.sleep(5)
