#!/opt/pwn.college/bash
# HARDENED-PATH
set -euo pipefail
IFS=' 	
'
unalias -a 2>/dev/null || true
unset BASH_ENV ENV CDPATH SHELLOPTS EDITOR VISUAL PAGER SYSTEMD_PAGER LESSOPEN GIT_EDITOR GIT_PAGER LD_PRELOAD LD_LIBRARY_PATH
PATH="/usr/sbin:/usr/bin:/sbin:/bin"; export PATH
umask 022

if [ "${0:0:1}" != "/" ]
then
	echo -e "${COLOR_RED}Incorrect...${COLORLESS}"
	echo "You did not call this challenge using an absolute path!"
	echo "An absolute path is anchored at the root of the filesystem, so it starts with /"
	exit 1
fi

echo -e "${COLOR_GREEN}Correct!!!${COLORLESS}"
echo "$0 is an absolute path! Here is your flag:"
/bin/cat /flag
