#!/bin/bash

fold -s <<< "You put a spaces after your '=' in your assignment! This caused the shell to execute the '$0' command instead of assigning it to the environment variable as you intended. Try again without spaces around '='!"
