#!/bin/bash

echo "bash: $0: command not found"
echo
fold -s <<< "It looks like you did not put quotes around the multi-word value in your variable assignment! This caused the shell to treat '$0' as a command. Quote your multi-word values!"
