#!/opt/pwn.college/bash
# HARDENED-PATH
set -euo pipefail
IFS=' 	
'
unalias -a 2>/dev/null || true
unset BASH_ENV ENV CDPATH SHELLOPTS EDITOR VISUAL PAGER SYSTEMD_PAGER LESSOPEN GIT_EDITOR GIT_PAGER LD_PRELOAD LD_LIBRARY_PATH
PATH="/usr/sbin:/usr/bin:/sbin:/bin"; export PATH
umask 022

if [ -t 1 ] || [ ! -f /tmp/subshell ]
then
	/usr/bin/fold -s >&2 <<< "You are not running me via Command Substitution! Please make sure to run me with command substitution."
	exit 1
elif [ ! -f /tmp/dstvar ]
then
	/usr/bin/fold -s >&2 <<< 'You do not appear to be reading into a variable... Make sure to read me into a variable, e.g.:'
	echo '    VAR_NAME=$(/challenge/run)' >&2
	exit 2
fi

[ -f /tmp/dstvar ] && read DSTVAR < /tmp/dstvar

if [ "$DSTVAR" != "PWN" ]
then
	/usr/bin/fold -s >&2 <<< "You are reading into the $DSTVAR variable, but you should read into the PWN variable. I am redacting the flag!"
	echo "pwn.college{REDACTED}"
	exit 3
fi

/usr/bin/fold -s >&2 <<< "Congratulations! You have read the flag into the PWN variable. Now print it out and submit it!"
/bin/cat /flag
